numero= input("Ingresa un número entero: ")
numero_entero= int(numero)
print("El numero es: ",numero_entero)
print("El tipo de dato es: ", type(numero_entero))

numero2= input("Ingresa un número decimal: ")
numero_decimal= float(numero2)
print("El numero es: ", numero_decimal)
print("El tipo de dato es: ", type(numero_decimal))

numero3= input("Ingresa un número: ")
print("El número es: ", numero3)
print("El tipo de dato original es: ", type(numero3))
numero_texto= str(numero3)
print("El tipo de dato convertido es: ", type(numero_texto))